# Generated by Django 5.1.1 on 2024-09-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Creative', '创新型企业'), ('Specialized', '专精特新'), ('LittleGiant', '专精特新小巨人')], default='geography', max_length=50),
        ),
    ]
