# Generated by Django 5.1.1 on 2024-09-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='symbol',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1),
        ),
    ]
