# Generated by Django 5.1.1 on 2024-09-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_choice_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(default='Please ask a question', max_length=255),
        ),
    ]
