# Generated by Django 5.1.1 on 2024-09-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_choice_score_alter_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='symbol_no',
            field=models.IntegerField(default=1),
        ),
    ]
