# Generated by Django 5.1.1 on 2024-09-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_choice_symbol_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='identifier',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Creative', '创新型企业'), ('Specialized', '专精特新'), ('LittleGiant', '专精特新小巨人')], default='Creative', max_length=50),
        ),
    ]
