# Generated by Django 5.1.1 on 2024-09-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_question_identifier_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='identifier',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
