# Generated by Django 5.1.1 on 2024-09-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='identifier',
        ),
    ]
