# Generated by Django 5.1.1 on 2024-09-18 09:34

import django.db.models.deletion
import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='client',
            field=models.ForeignKey(default=questions.models.get_default_client, on_delete=django.db.models.deletion.CASCADE, to='questions.client'),
        ),
    ]
