# Generated by Django 5.1.1 on 2024-09-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0014_question_display_order_alter_question_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('question', 'symbol')},
        ),
    ]
